local lyricalation = 2
-- 0 = all, 1 = lunaware vs stas, 2 = wanwood vs 2j0y, 3 = hua vs werth, 4 = francis vs kekse, 5 = snas vs rome, 6 = j_mey vs rome
local TextChatService = game:GetService("TextChatService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local function SendChatMessage(message)
	local debugMessage = "" .. message
	if TextChatService.ChatVersion == Enum.ChatVersion.TextChatService then
		local textChannel = TextChatService.TextChannels:FindFirstChild("RBXGeneral")
		if textChannel then
			textChannel:SendAsync(debugMessage)
		end
	else
		local chatEvent = game:GetService("ReplicatedStorage"):FindFirstChild("DefaultChatSystemChatEvents")
		if chatEvent then
			chatEvent.SayMessageRequest:FireServer(debugMessage, "All")
		end
	end
end

local RAPBATTLESOFHISTORY = {
	{
		"Epic clam battles of history",
		"Lunaware VS Sasikmegaaaaaaaaaaaa",
		"Begin",
		"I am the anticheat of redd",
		"No other skid can stand up to me",
		"I have starscripts the best script ever you see",
		"I am the king of the electric state",
		"No one can defeat me",
		"My hacking skills are unmatched",
		"Im always ahead you see",
		"I dont care about the laws",
		"I dont play by their rules",
		"My only goal is too win",
		"And ill do whatever it takes to fool",
		"My methods may be unorthodox",
		"But i always come out on top",
		"If you wanna be like me",
		"Just remember to never stop",
		"So if you want to be the best",
		"Just follow my lead",
		"Dont let anyone tell you what to do, concede",
		"Keep pushing forward and youll achieve your goals",
		"With Stasikmega by your side",
		"Youll be unstoppable, thats my role",
		"LUNAWARE",
		"The master of exploitation in the realm of the electric state",
		"Behold my power for i have laid waste for es time and again",
		"Sealing their fate, i am lunaware",
		"The indomitable force undefeated and renoun",
		"With the apollo client in my grasp",
		"No one dares to stand on my battleground",
		"My exploits are legendary",
		"My dominion unrivaled",
		"I bend the rules of this digital realm",
		"Leaving opponents disheveled",
		"Through cunning and skill",
		"I navigate the code",
		"Unleashing chaos and destruction wherever i strode",
		"No defenses can thwart me",
		"No firewalls can hold, I exploit vulnerabilities",
		"Turning security to gold",
		"The electric state trembles to the sound of my name",
		"For i am lunaware, The harvinger of their shame",
		"Witness my reign as i conquer their domain",
		"Their febel attempts to resist all in vain",
		"I manipulate, infiltrate and dismantle their might",
		"Leaving them vulnerable, trapped in eternal night",
		"So heed my words you foolish foes",
		"For lunawares power only grows",
		"I am the epitome of machiavellian might",
		"And electric state shall succumb from my ruthless insight",
		"Who won?",
		"Whos next?",
	},
	{
		"Epic clam battles of history",
		"Wanwood vs 2j0000000000000y",
		"Begin",
		"Wanwood, you cant stop my ban hammer",
		"For i will strike you down with such that you clamour",
		"My kittens untouched for your exploits cannot reach them",
		"My weight blocks your weight for your exploits are weak",
		"Providence will not protect you Wanwood for my body",
		"weight crushes all that stands in my way",
		"fight all you want but you will never get past to my kittens",
		"I wam wanwood, you stand no change against clam x 2J0Y",
		"My clams stay strong for your body weight doesn't",
		"You think eating 5 double burgers with added flavor can stop me?",
		"Your body is fatter than your mother; How did i know?",
		"I'm omnipotent and not even that can describe your weight",
		"None of your kittens are safe from my limestone",
		"Wanwood, tremble before my ruthless ban hammer",
		"For it strikes with a force that makes you stammer",
		"My kittens, untouched by your feeble endeavors",
		"Remain shielded from your futile and weak measures",
		"Your weight, insignificant against my might",
		"Crumbles beneath my body, a true weight of fight",
		"No devine providence can save you, Wanwood",
		"As my sheer weight crushes all who dare to intrude.",
		"Engage in battle as you may, but's all in vain",
		"For you shall never overcome the barrier to my kittens' domain",
		"2JOY my massive limestone cube can easily crush your orb-like body",
		"You have a s jexual attraction towards traps fatter than you",
		"How disgusting",
		'While me Wanwood does not need your so called "kittens" to function',
		"As i have the fart gas in my grasp",
		"My limestone will bisect your kittens",
		"A clean cut with such a large stone",
		"looks like your kittens are just as fat as you",
		"What a shame that you cant attract anyone that isnt a",
		"Fwucj cing j Ni kys gg kys er",
		"Tremble, fools, in the wake of my dominion",
		"For my power knows no bounds, a relentless opinion",
		"Your feeble attempts, like whispers in the breeze",
		"Cannot break the walls that guard my cherished sleaze",
		"A fortress of darkness, where darkness thrives",
		"Your efforts to penetrate it, oh how it deprives",
		"No gods, no fate, shall deter my reign",
		"As i trample over wanwood, inflicting eternal pain",
		"Engage in battles of futility, you desperate few",
		"But my kittens remain unscathed, forever anew",
		"For i am the puppeteer pulling every string",
		"To protect my wicked realm, my evil king",
		"Beware the wrath that i shall unleash",
		"My wickedness, relentless, shall never cease",
		"So tremble before me, for I hold the key",
		"To a world where my darkness reigns, eternally",
		"Your reign cannot withstand a limestone cube",
		"What is a reign if it crumbes from your own weight?",
		"2JOY I would say you are too jewish",
		"Your reign is foolish",
		"Not even your kittens can get close to you",
		"Looks like borders have been established for you",
		"Who won?",
		"Whos next?",
	},
	{
		"Epic clam battles of history",
		"Hua vs Werth",
		"Begin",
		"I am Hua, a force to reckon",
		"With four children locked, none have beckoned",
		"No escape from my unwavering hold",
		"An army of exploiters, my story unfolds",
		"Three clans for erping, a realm of pleasure",
		"While you, dear foe, possess none to treasure",
		"My dominance prevails, you stand no chance",
		"For I am hua, the ruler of erp",
		"Hua Do you believe your erp's profound?",
		"I am werth, the god of erp",
		"My erp dwells in realms of RTX HD, renowned",
		"With child flavor added, a daring feast",
		"And a four-stack burger in my belly, beast unleashed",
		"Crushing foes under my weight, they tremble in despair",
		"For I conquer all with my erp",
		"I reign supreme, Hua, the sovereign of might",
		"My erp kingdom stands, an unyielding sight",
		"Exploiters on my side, their souls I control",
		"No mercy granted, as I assert my role",
		"destined for disdain",
		"My exploiters overwhelm a power you can't thwart",
		"For Hua, the erp ruler, holds fort",
		"Your exploiters were crushed by my four-stack burger weight",
		"They now dwell in my stomach",
		"Feed me more of your exploiters, keep trying",
		"for I will consume all there is to your erp",
		"and feed it to my erp",
		"Who won?",
		"Whos next?",
	},
	{
		"Epic clam battles of history",
		"Francis vs Kekseeeeeeee",
		"Look who it is!",
		"So called king of pe JX do m files",
		"What are you?",
		"A sequel of arthritis renowned?",
		"Fracis you can't even touch chilj dren with your inoperative hands",
		"Guess you're overdoj ign on creth",
		"Francis I never knew that you were french",
		"surrendering to me that rotten sej men stained bed sheet",
		"Kekse you sound like a dying old man",
		"You cant breathe! Looks like george flj oyd is making a return",
		"You lose your grooming potential on doing #####",
		"I gain a check in my bank account selling ###### to children",
		"Oh kekse you make everyone in the Redd general go kek ",
		"As you try to sj ucj k your own 1 inch ######",
		"No wonder why you want some kids on that tip",
		"Oh your so broke your little b  L#alls shroke",
		"I am making 6 figures off of chicken coin",
		"WHile you are out there sellings #####s to",
		"Middle schoolers as a highschool dropout",
		"I cant breathe? Look at your lungs",
		"Ravaged by your own #####s",
		"If guinness world records has a record for grj oojming children",
		"I would be at the very top unlike you, smitten",
		"Only thing you'd be at the top is the shekel count leaderboards",
		"You smelly jude",
		"Gonna come to ohio to gas your Judist asjs",
		"Call me dj adjdy hj itjlej r, wannabe dictator of grj oojming",
		"While youre doing that that im getting an infinite amount of children",
		"on my deformed grainy black three inch cj o jck",
		"Better shove it up your rotten sej men and ",
		"bloody diarrhea filled bju ttj hjole",
		"Im the new edp445 and you're never gonna compare",
		"I could best edp445 with just 1% of my grj oojming power",
		"Cant gro zzoom children without buying a stack of dji ljdos?",
		"Pjss all over your own pants if they can even contain more",
		"For i, the most infamous grj oojmer ",
		"Will slap you back down where you came",
		"You are old and your hands cant move an inch",
		"I will be the new king of beedophiles as i can touch",
		"Children however i want",
		"The entire world wants to touch my tip",
		"Youre just another irrelevant blip",
		"Who is this ni kys gg kys er coming at me",
		"Thinking he can grj oojm minors like me?",
		"No beedophile dethrones FrancisTheCutie",
		"Im a 32 year old man, still got fresh batches of kiddies",
		"You grj oojmed one man, found out he was 20 years old",
		"Guess you will never lay your hands on children",
		"Like i do for a living",
		"I can always shove dog pje njis shaped dji ljdjos up oyur moms throat",
		"I can sense her fat a mile away, which rivals that which werth has",
		"[Epic transition to kekse vs werth]",
		"Man i thought that njijggja",
		"I see two ni ji kys gg kys as looking to be the god of erp",
		"But no one except for me can claim that title",
		"Already dropped one faster than i rj zajped Hua, Kekse youre next",
		"I have 100 kittens under my massive belt",
		"All freshly grj oomjed whilst you struggle to",
		"contain a single hj ormonal teenager",
		"Gonna turn you into my next four patty stack burger,",
		"you beedophilic twj ink",
		"What is this fat slug that has come out of the sky",
		"I thought Jabba the Hutt died in return of the Jedi",
		"Bro thinking hes a god of erp ",
		"whilst im the most infamous grj oojmer of all time",
		"500 children, fresh out of the newest grj oojming batch",
		"a true delight fit for a king, quite fit for me indeed",
		"When i get done with your fat asjs even 2J0Y cant compare to",
		"Ill claim your kittens as a trophy over my triumph of an excuse",
		'of a so-called "god of erp" you are',
		'Your title of "most infamous grj oomjer" pales in comparison',
		"to my four stack burger weight",
		"Kekse, no one can save you from my abilities in the erp field",
		"Ill feed from your erp to grow my own erp ",
		"And add you to my beltof kittens",
		"Sjh jit your pants as the god of erp, werth is here",
		"and hes about to feast",
		"Who won?",
		"Whos next?",
	},
	{
		"Epic clam battles of historyyyyyyyy",
		"snas_Kid vs. ROOOOMEFAAAALLLLLSSSS",
		"BEGIN!",
		"snas_Kid101: Step back romefalls, I keep the server clean,",
		"snas_Kid101: You're just a glitch in my code, a pathetic machine.",
		"romefalls: You swing bans like hammers but I slip through the cracks,",
		"romefalls: While you're chasing ghosts, I'm draining your stacks.",
		"snas_Kid101: I run logs like a god, your exploits are weak,",
		"snas_Kid101: One line in the console, you're gone in a streak.",
		"romefalls: You're a rent-a-cop tyrant with a keyboard badge,",
		"romefalls: I ghost through your walls like a digital mirage.",
		"snas_Kid101: I’ve seen your kind, script kiddie decay,",
		"snas_Kid101: A permaban payload coming your way.",
		"romefalls: I rewrite the rules, make the laws obey,",
		"romefalls: Your sandbox is mine, I make admins pray.",
		"snas_Kid101: You're a bug in the wires, I'm the firewall flare,",
		"snas_Kid101: I purge rats like you from Electric State air.",
		"romefalls: You're a cog in the system, I'm entropy's flame,",
		"romefalls: When this server dies, they'll remember my name.",
		"snas_Kid101: Remember your name? You're a footnote glitch,",
		"snas_Kid101: A two-bit pest with a copy-paste itch.",
		"romefalls: You cling to your rules like they're sacred scripts,",
		"romefalls: But I bend every byte till the whole world flips.",
		"snas_Kid101: Your packets are noise, mine resonate clean,",
		"snas_Kid101: I'm the last line of code between order and obscene.",
		"romefalls: You're a puppet in blue with no strings of your own,",
		"romefalls: While I jailbreak the sky from my digital throne.",
		"snas_Kid101: You sit in the dark thinking chaos is might,",
		"snas_Kid101: But I bring down the banhammer cloaked in light.",
		"romefalls: Cloaked in light? You're blind to the game,",
		"romefalls: I rewrite reality while you chase fame.",
		"snas_Kid101: I don't chase, I hunt , I surveil and I strike,",
		"snas_Kid101: You're a glitch in a loop, I’m a system-wide spike.",
		"romefalls: Your system's decayed, it's built on delay,",
		"romefalls: I bring zero-day wrath to your power-play.",
		"snas_Kid101: Then bring it , I’ll trace it, I log every sin,",
		"snas_Kid101: When the packets settle, the mod always wins.",
		"Who Won?",
		"Who's Next ?",
	},
	{
		"Epic clam battles of historryyyyyyy ahhhh",
		"J_MEY vs. ROOOOOMEFAAALLLLSSSSSSSSSS",
		"BEGIN!",
		"J_mey: Zylock? Nah, that’s just a smokescreen name,",
		"J_mey: I'm J_mey, and I'll bury you in this game.",
		"romefalls: Smokescreen? Please, I see through the lies,",
		"romefalls: You’re just a dev’s shadow in a moderator’s disguise.",
		"J_mey: You're obsessed with the code, but I run this place,",
		"J_mey: I'll ban you so fast, you won't even see my face.",
		"romefalls: You think you control? I slip through the cracks,",
		"romefalls: You're just a glitch in the system, and I’m your attack.",
		"J_mey: You exploit, but I’m the one who sets the rules,",
		"J_mey: A script kiddie like you can’t escape the tools.",
		"romefalls: I make your logs scream, I leave nothing behind,",
		"romefalls: You're a puppet in code, I control your mind.",
		"J_mey: Puppet? Nah, I pull strings, I’m the one who decides,",
		"J_mey: You’re just a failure, hiding behind your lies.",
		"romefalls: You act like you’re smart, but your system’s flawed,",
		"romefalls: When I hit it, it crashes, I leave it all raw.",
		"J_mey: You can crash and you can break, but I’ll always rebuild,",
		"J_mey: I’m the last line of defense when your exploits are killed.",
		"romefalls: Rebuild all you want, your code is full of holes,",
		"romefalls: I slip through undetected, while you lose control.",
		"J_mey: Lose control? I’ve already won this fight,",
		"J_mey: You’re just a blip in my radar, lost to the night.",
		"romefalls: You can ban all you want, but I’ll be back again,",
		"romefalls: I’m a virus in your code, I’ll never be slain.",
		"J_mey: Never be slain? You're a loop with no end,",
		"J_mey: But loops get patched, and I don’t pretend.",
		"romefalls: You patch one hole, I spawn ten more,",
		"romefalls: I'm entropy incarnate, I was made for war.",
		"J_mey: War? You brought exploits to a dev-made world,",
		"J_mey: I bring rollback thunder, your scripts get hurled.",
		"romefalls: Dev-made or not, you're Rylock's clone,",
		"romefalls: A proxy enforcer with no will of your own.",
		"J_mey: Think what you want, but the bans still stick,",
		"J_mey: You’re a ghost in the logs, gone in one click.",
		"romefalls: Click all you want, I don't play by your laws,",
		"romefalls: I fracture your frame with a silent cause.",
		"J_mey: Your silent cause dies in a stack trace burn,",
		"J_mey: I audit your chaos with each server turn.",
		"romefalls: Keep auditing, puppet, I feed on delay,",
		"romefalls: Your empire runs lagged, while I rewrite play.",
		"J_mey: Rewrite all you want, it loops back to me,",
		"J_mey: I’m the architect watching from line forty-three.",
		"romefalls: Then watch close, old mod, your scripts are stale,",
		"romefalls: I execute fresh, while your watchdogs fail.",
		"J_mey: You’re noise. I’m order. I silence your storm,",
		"J_mey: When I purge the exploit, the server’s reborn.",
		"romefalls: Reborn in chains, a sandbox of fear,",
		"romefalls: I tear through your rules till the code runs clear.",
		"J_mey: Your clarity’s chaos, just fragments and bugs,",
		"J_mey: I lock down the source, no room for thugs.",
		"romefalls: You lock down nothing, just slow the decay,",
		"romefalls: I shift with the runtime, slip past your array.",
		"J_mey: I don’t chase shadows, I map every trace,",
		"J_mey: One packet from you and I hard-freeze your base.",
		"romefalls: Then freeze me, I’ll fork, I live in the breach,",
		"romefalls: While you quote protocols like a priest giving speech.",
		"J_mey: Protocols work. That’s why you rage,",
		"J_mey: Banned on sight, you rot offstage.",
		"romefalls: Rot? No, I root. I embed and expand,",
		"romefalls: While your admin suite crumbles in hand.",
		"J_mey: Crumbles? I wrote the permissions you fear,",
		"J_mey: You hit walls while I script what’s near.",
		"romefalls: Your scripts are static, I evolve with each run,",
		"romefalls: A logic bomb ticking, your purge just begun.",
		"J_mey: You tick all you want, I sandbox the blast,",
		"J_mey: I mirror your method, then delete it fast.",
		"romefalls: Then delete me, see if the silence holds,",
		"romefalls: I’m the exploit whisper, embedded in folds.",
		"J_mey: You whisper in scripts, I shout in the core,",
		"J_mey: This server’s not yours. Not now. Nevermore.",
		"romefalls: Nevermore? You quoting poems now too?",
		"romefalls: While I rewrite your backend in plain Lua blue.",
		"J_mey: You can quote my silence, but the logs say more,",
		"J_mey: I’ve banned you thrice , I’ll make it four.",
		"romefalls: Logs lie, memory fades, but I stay etched,",
		"romefalls: I hardcode decay, your power’s far-stretched.",
		"J_mey: Far-stretched? I built this net you're breaking,",
		"J_mey: Every exploit you run, I see it waking.",
		"romefalls: And still I run , proof that you’re bluffing,",
		"romefalls: Your throne’s made of flags, mine of something.",
		"J_mey: Something? You’re noise,no purpose, no path,",
		"J_mey: Just malformed packets and unstable math.",
		"romefalls: Malformed to you, but perfect to me,",
		"romefalls: I’m the rootkit mind you’ll never unsee.",
		"J_mey: I see you now, and I always will,",
		"J_mey: Every line you cross leads to a kill.",
		"romefalls: You think you’re above, you think you’re clean,",
		"romefalls: But your name rides shadows on every scene.",
		"J_mey: Shadows don’t scare me , I work in the light,",
		"J_mey: I’m the server’s last watch, its firewall knight.",
		"romefalls: Then die with your light , your time just expired,",
		"romefalls: I breached your crown, your rank’s been retired.",
		"romefalls: I flipped your stack, and I own your stage,",
		"romefalls: This world runs on chaos , welcome to the age.",
	},
}

for _, battle in lyricalation == 0 and RAPBATTLESOFHISTORY or { RAPBATTLESOFHISTORY[lyricalation] } do
	for __, lyric in battle do
		SendChatMessage(`/ad {lyric}`)
		task.wait(3)
	end
end
