local lyricalation = 1
-- 0 = all, 1 = lunaware vs stas, 2 = wanwood vs 2j0y, 3 = hua vs werth, 4 = francis vs kekse
local TextChatService = game:GetService("TextChatService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local function SendChatMessage(message)
	local debugMessage = "" .. message
	if TextChatService.ChatVersion == Enum.ChatVersion.TextChatService then
		local textChannel = TextChatService.TextChannels:FindFirstChild("RBXGeneral")
		if textChannel then
			textChannel:SendAsync(debugMessage)
		end
	else
		local chatEvent = game:GetService("ReplicatedStorage"):FindFirstChild("DefaultChatSystemChatEvents")
		if chatEvent then
			chatEvent.SayMessageRequest:FireServer(debugMessage, "All")
		end
	end
end

local RAPBATTLESOFHISTORY = {
	{
		"Epic clam battles of history",
		"Lunaware VS Sasikmegaaaaaaaaaaaa",
		"Begin",
		"I am the anticheat of redd",
		"No other skid can stand up to me",
		"I have starscripts the best script ever you see",
		"I am the king of the electric state",
		"No one can defeat me",
		"My hacking skills are unmatched",
		"Im always ahead you see",
		"I dont care about the laws",
		"I dont play by their rules",
		"My only goal is too win",
		"And ill do whatever it takes to fool",
		"My methods may be unorthodox",
		"But i always come out on top",
		"If you wanna be like me",
		"Just remember to never stop",
		"So if you want to be the best",
		"Just follow my lead",
		"Dont let anyone tell you what to do, concede",
		"Keep pushing forward and youll achieve your goals",
		"With Stasikmega by your side",
		"Youll be unstoppable, thats my role",
		"LUNAWARE",
		"The master of exploitation in the realm of the electric state",
		"Behold my power for i have laid waste for es time and again",
		"Sealing their fate, i am lunaware",
		"The indomitable force undefeated and renoun",
		"With the apollo client in my grasp",
		"No one dares to stand on my battleground",
		"My exploits are legendary",
		"My dominion unrivaled",
		"I bend the rules of this digital realm",
		"Leaving opponents disheveled",
		"Through cunning and skill",
		"I navigate the code",
		"Unleashing chaos and destruction wherever i strode",
		"No defenses can thwart me",
		"No firewalls can hold, I exploit vulnerabilities",
		"Turning security to gold",
		"The electric state trembles to the sound of my name",
		"For i am lunaware, The harvinger of their shame",
		"Witness my reign as i conquer their domain",
		"Their febel attempts to resist all in vain",
		"I manipulate, infiltrate and dismantle their might",
		"Leaving them vulnerable, trapped in eternal night",
		"So heed my words you foolish foes",
		"For lunawares power only grows",
		"I am the epitome of machiavellian might",
		"And electric state shall succumb from my ruthless insight",
		"Who won?",
		"Whos next?",
	},
	{
		"Epic clam battles of history",
		"Wanwood vs 2j0000000000000y",
		"Begin",
		"Wanwood, you cant stop my ban hammer",
		"For i will strike you down with such that you clamour",
		"My kittens untouched for your exploits cannot reach them",
		"My weight blocks your weight for your exploits are weak",
		"Providence will not protect you Wanwood for my body",
		"weight crushes all that stands in my way",
		"fight all you want but you will never get past to my kittens",
		"I wam wanwood, you stand no change against clam x 2J0Y",
		"My clams stay strong for your body weight doesn't",
		"You think eating 5 double burgers with added flavor can stop me?",
		"Your body is fatter than your mother; How did i know?",
		"I'm omnipotent and not even that can describe your weight",
		"None of your kittens are safe from my limestone",
		"Wanwood, tremble before my ruthless ban hammer",
		"For it strikes with a force that makes you stammer",
		"My kittens, untouched by your feeble endeavors",
		"Remain shielded from your futile and weak measures",
		"Your weight, insignificant against my might",
		"Crumbles beneath my body, a true weight of fight",
		"No devine providence can save you, Wanwood",
		"As my sheer weight crushes all who dare to intrude.",
		"Engage in battle as you may, but's all in vain",
		"For you shall never overcome the barrier to my kittens' domain",
		"2JOY my massive limestone cube can easily crush your orb-like body",
		"You have a s jexual attraction towards traps fatter than you",
		"How disgusting",
		"While me Wanwood does not need your so called \"kittens\" to function",
		"As i have the fart gas in my grasp",
		"My limestone will bisect your kittens",
		"A clean cut with such a large stone",
		"looks like your kittens are just as fat as you",
		"What a shame that you cant attract anyone that isnt a",
		"Fwucj cing j Ni kys gg kys er",
		"Tremble, fools, in the wake of my dominion",
		"For my power knows no bounds, a relentless opinion",
		"Your feeble attempts, like whispers in the breeze",
		"Cannot break the walls that guard my cherished sleaze",
		"A fortress of darkness, where darkness thrives",
		"Your efforts to penetrate it, oh how it deprives",
		"No gods, no fate, shall deter my reign",
		"As i trample over wanwood, inflicting eternal pain",
		"Engage in battles of futility, you desperate few",
		"But my kittens remain unscathed, forever anew",
		"For i am the puppeteer pulling every string",
		"To protect my wicked realm, my evil king",
		"Beware the wrath that i shall unleash",
		"My wickedness, relentless, shall never cease",
		"So tremble before me, for I hold the key",
		"To a world where my darkness reigns, eternally",
		"Your reign cannot withstand a limestone cube",
		"What is a reign if it crumbes from your own weight?",
		"2JOY I would say you are too jewish",
		"Your reign is foolish",
		"Not even your kittens can get close to you",
		"Looks like borders have been established for you",
		"Who won?",
		"Whos next?",
	},
	{
		"Epic clam battles of history",
		"Hua vs Werth",
		"Begin",
		"I am Hua, a force to reckon",
		"With four children locked, none have beckoned",
		"No escape from my unwavering hold",
		"An army of exploiters, my story unfolds",
		"Three clans for erping, a realm of pleasure",
		"While you, dear foe, possess none to treasure",
		"My dominance prevails, you stand no chance",
		"For I am hua, the ruler of erp",
		"Hua Do you believe your erp's profound?",
		"I am werth, the god of erp",
		"My erp dwells in realms of RTX HD, renowned",
		"With child flavor added, a daring feast",
		"And a four-stack burger in my belly, beast unleashed",
		"Crushing foes under my weight, they tremble in despair",
		"For I conquer all with my erp",
		"I reign supreme, Hua, the sovereign of might",
		"My erp kingdom stands, an unyielding sight",
		"Exploiters on my side, their souls I control",
		"No mercy granted, as I assert my role",
		"destined for disdain",
		"My exploiters overwhelm a power you can't thwart",
		"For Hua, the erp ruler, holds fort",
		"Your exploiters were crushed by my four-stack burger weight",
		"They now dwell in my stomach",
		"Feed me more of your exploiters, keep trying",
		"for I will consume all there is to your erp",
		"and feed it to my erp",
		"Who won?",
		"Whos next?",
	},
	{
		"Epic clam battles of history",
		"Francis vs Kekseeeeeeee",
		"Look who it is!",
		"So called king of pe JX do m files",
		"What are you?",
		"A sequel of arthritis renowned?",
		"Fracis you can't even touch chilj dren with your inoperative hands",
		"Guess you're overdoj ign on creth",
		"Francis I never knew that you were french",
		"surrendering to me that rotten sej men stained bed sheet",
		"Kekse you sound like a dying old man",
		"You cant breathe! Looks like george flj oyd is making a return",
		"You lose your grooming potential on doing #####",
		"I gain a check in my bank account selling ###### to children",
		"Oh kekse you make everyone in the Redd general go kek ",
		"As you try to sj ucj k your own 1 inch ######",
		"No wonder why you want some kids on that tip",
		"Oh your so broke your little b  L#alls shroke",
		"I am making 6 figures off of chicken coin",
		"WHile you are out there sellings #####s to",
		"Middle schoolers as a highschool dropout",
		"I cant breathe? Look at your lungs",
		"Ravaged by your own #####s",
		"If guinness world records has a record for grj oojming children",
		"I would be at the very top unlike you, smitten",
		"Only thing you'd be at the top is the shekel count leaderboards",
		"You smelly jude",
		"Gonna come to ohio to gas your Judist asjs",
		"Call me dj adjdy hj itjlej r, wannabe dictator of grj oojming",
		"While youre doing that that im getting an infinite amount of children",
		"on my deformed grainy black three inch cj o jck",
		"Better shove it up your rotten sej men and ",
		"bloody diarrhea filled bju ttj hjole",
		"Im the new edp445 and you're never gonna compare",
		"I could best edp445 with just 1% of my grj oojming power",
		"Cant gro zzoom children without buying a stack of dji ljdos?",
		"Pjss all over your own pants if they can even contain more",
		"For i, the most infamous grj oojmer ",
		"Will slap you back down where you came",
		"You are old and your hands cant move an inch",
		"I will be the new king of beedophiles as i can touch",
		"Children however i want",
		"The entire world wants to touch my tip",
		"Youre just another irrelevant blip",
		"Who is this ni kys gg kys er coming at me",
		"Thinking he can grj oojm minors like me?",
		"No beedophile dethrones FrancisTheCutie",
		"Im a 32 year old man, still got fresh batches of kiddies",
		"You grj oojmed one man, found out he was 20 years old",
		"Guess you will never lay your hands on children",
		"Like i do for a living",
		"I can always shove dog pje njis shaped dji ljdjos up oyur moms throat",
		"I can sense her fat a mile away, which rivals that which werth has",
		"[Epic transition to kekse vs werth]",
		"Man i thought that njijggja",
		"I see two ni ji kys gg kys as looking to be the god of erp",
		"But no one except for me can claim that title",
		"Already dropped one faster than i rj zajped Hua, Kekse youre next",
		"I have 100 kittens under my massive belt",
		"All freshly grj oomjed whilst you struggle to",
		"contain a single hj ormonal teenager",
		"Gonna turn you into my next four patty stack burger,",
		"you beedophilic twj ink",
		"What is this fat slug that has come out of the sky",
		"I thought Jabba the Hutt died in return of the Jedi",
		"Bro thinking hes a god of erp ",
		"whilst im the most infamous grj oojmer of all time",
		"500 children, fresh out of the newest grj oojming batch",
		"a true delight fit for a king, quite fit for me indeed",
		"When i get done with your fat asjs even 2J0Y cant compare to",
		"Ill claim your kittens as a trophy over my triumph of an excuse",
		"of a so-called \"god of erp\" you are",
		"Your title of \"most infamous grj oomjer\" pales in comparison",
		"to my four stack burger weight",
		"Kekse, no one can save you from my abilities in the erp field",
		"Ill feed from your erp to grow my own erp ",
		"And add you to my beltof kittens",
		"Sjh jit your pants as the god of erp, werth is here",
		"and hes about to feast",
		"Who won?",
		"Whos next?",
	}
}

for _, battle in lyricalation == 0 and RAPBATTLESOFHISTORY or {RAPBATTLESOFHISTORY[lyricalation]} do
	for __, lyric in battle do
		SendChatMessage(`/ad {lyric}`)
		task.wait(3)
	end
end